#!/usr/bin/env sh

# NOTE: after yabai update, reconfigure scripting addon, see: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.25
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8
yabai -m config window_border off
yabai -m config insert_feedback_color 0xffd75f5f

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

echo "yabai configuration loaded.."
