[data]
  aerc_mail_email = ""
  aerc_mail_outgoing = ""
  aerc_mail_source = ""
  git_email = ""
  khal_calendar_path = ""
  khard_addressbook_path = ""
  newsboat_login = ""
  newsboat_password = ""
  newsboat_url = ""
  offlineimap_mail_localfolders =  ""
  offlineimap_mail_remote_pass_entry =  ""
  offlineimap_mail_remotehost =  ""
  spotify_username = ""
  spotifyd_pass_entry = ""
[diff]
    format = "git"
    pager = "diff-so-fancy"
