" Add XDG base -folders to runtimepath so vim is able to load settings and 
" plugins
set runtimepath+=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

" Load all configuration files
" Remap -> plugins -> general are dependent, so order is specific
runtime remappings.vim
runtime plugins.vim
runtime general.vim
